# Generated by Django 4.2.1 on 2023-06-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField(max_length=256)),
                ('start_time', models.TimeField(max_length=256)),
                ('end_time', models.TimeField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
    ]
