# Generated by Django 4.2.1 on 2023-06-04 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
